// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7hLfQPv-cCrKvxSs5C8x1vWdlldB__34',
    appId: '1:527423928116:web:4e68b8ee5e06131650d761',
    messagingSenderId: '527423928116',
    projectId: 'financas-app-ba040',
    authDomain: 'financas-app-ba040.firebaseapp.com',
    storageBucket: 'financas-app-ba040.appspot.com',
    measurementId: 'G-KRC77EDT0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzrGU_ep2_J7KMH6HojaB3k5u8oAZnx_Y',
    appId: '1:527423928116:android:5f55257f19bccebb50d761',
    messagingSenderId: '527423928116',
    projectId: 'financas-app-ba040',
    storageBucket: 'financas-app-ba040.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrB37D6ph1DDmX_-w-1Qph7mMtYCmLNHI',
    appId: '1:527423928116:ios:13bff2b78623f4e450d761',
    messagingSenderId: '527423928116',
    projectId: 'financas-app-ba040',
    storageBucket: 'financas-app-ba040.appspot.com',
    iosBundleId: 'com.example.financasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrB37D6ph1DDmX_-w-1Qph7mMtYCmLNHI',
    appId: '1:527423928116:ios:a3e9de530562ec8650d761',
    messagingSenderId: '527423928116',
    projectId: 'financas-app-ba040',
    storageBucket: 'financas-app-ba040.appspot.com',
    iosBundleId: 'com.example.financasApp.RunnerTests',
  );
}
